version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - front-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    networks:
      - back-network
      - front-network

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - back-network

volumes:
  db-data:

networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge