version: "3.8"

services:
  frontend:
    build: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - front-network

  backend:
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=pixelStore_database
      - DATABASE_USER=student
      - DATABASE_PASSWORD=student
      - DJANGO_SETTINGS_MODULE=config.settings
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:8000/ || true" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - back-network
      - front-network

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: pixelStore_database
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ustudent", "-pstudent"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - back-network

volumes:
  db-data:

networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge
