version: "3.8"

services:
  backend:
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_HOST= ${DATABASE_HOST}
      - DATABASE_PORT= ${DATABASE_PORT}
      - DATABASE_NAME= ${DATABASE_NAME}
      - DATABASE_USER= ${DATABASE_USER}
      - DATABASE_PASSWORD= ${DATABASE_PASSWORD}
      - DJANGO_SETTINGS_MODULE= config.settings_test
    command: pytest
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:8000/ || true" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - back-network

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD = ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE = ${MYSQL_DATABASE}
      - MYSQL_USER = ${MYSQL_USER}
      - MYSQL_PASSWORD = ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-test-data:/var/lib/mysql
      - ./database_test:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ustudent", "-pstudent"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - back-network

volumes:
  db-test-data:

networks:
  back-network:
    driver: bridge
